# Paleta de Cores VINTAGE para o AiNOMEATOR
[Cores]
vocal_principal = #CC4E3E
backing_vocals = #DC826E
bateria = #5A7387
percussao = #8CA0A0
baixo = #645046
guitarra_eletrica = #738764
violao = #A59678
teclado = #D7A05A
synth = #BE876E
cordas = #916950
sopros = #B46E78
efeitos = #8C8C82
pastas = #4B4641
outro = #827D78
