# Paleta de Cores ORANGE para o AiNOMEATOR
[Cores]
vocal_principal = #FF6400
backing_vocals = #FFA05A
bateria = #823200
percussao = #B45A1E
baixo = #3C1900
guitarra_eletrica = #DC500A
violao = #F08232
teclado = #FAB450
synth = #FFD278
cordas = #96552D
sopros = #D27850
efeitos = #8C7D6E
pastas = #3C322D
outro = #877D78
