# Paleta de Cores GREEN para o AiNOMEATOR
[Cores]
vocal_principal = #64B464
backing_vocals = #8CC88C
bateria = #224C22
percussao = #3C7850
baixo = #6B8E23
guitarra_eletrica = #2E8B57
violao = #8FBC8F
teclado = #B4D278
synth = #78C8A0
cordas = #556B2F
sopros = #9ACD32
efeitos = #708C78
pastas = #2D3C32
outro = #829687
