# Paleta de Cores PURPLE para o AiNOMEATOR
[Cores]
vocal_principal = #D264D2
backing_vocals = #E6A0E6
bateria = #4B0082
percussao = #8A2BE2
baixo = #301934
guitarra_eletrica = #9370DB
violao = #BA55D3
teclado = #D8BFD8
synth = #7B68EE
cordas = #9932CC
sopros = #DA70D6
efeitos = #786E8C
pastas = #322D3C
outro = #8C8296
